version: "3.5"
services:
  app:
    image: routs-api:test
    environment:
      - ROUTSDB_URL=postgres://root:routseip@db-prod.c9gmgglqqaod.eu-west-3.rds.amazonaws.com:4343/api_prod
      - JWT_SECRET=JePratiqueUnPeuKibana2018
      - HASH_SEED=10
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
      restart_policy:
        condition: none
    ports:
      - target: 3000
        published: 80
        protocol: tcp
        mode: host
      - target: 4242
        published: 4242
        protocol: tcp
        mode: host
