FROM node:10

RUN mkdir /app
WORKDIR /app
ADD . /app

USER root

RUN npm install
RUN npm install -g serve
RUN npm run build

EXPOSE 3000
EXPOSE 80
EXPOSE 4242
EXPOSE 8081
EXPOSE 8080

CMD ["serve", "-s", "dist"]
