version: "3.5"
services:
  app:
    image: michaelboublil/routs-editor:prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 5000
        published: 8081
        protocol: tcp
        mode: host
